name: Injection via Action Param

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Typper deploy (with injected payload)
        uses: typper-io/figma-plugin-deploy@v1
        with:
          plugin-id: "abc"
          team-id: "def"
          release-notes: "Injected Value: $(echo INJECTION_SUCCESSFUL)"
        env:
          FIGMA_EMAIL: dummy@example.com
          FIGMA_PASSWORD: dummy
          FIGMA_TOTP_SECRET: dummy
